apiVersion: charts.nginx.org/v1alpha1
kind: NginxIngress
metadata:
  name: nginxingress-sample
  namespace: nginx-ingress-operator-system
spec:
  controller:
    defaultTLS:
      secret: ""
    image:
      pullPolicy: IfNotPresent
      repository: nginx/nginx-ingress
      tag: 3.1.1-ubi
    ingressClass: nginx
    kind: deployment
    nginxplus: false
    replicaCount: 1
    serviceAccount:
      imagePullSecretName: ""