iapiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 6Gi
  gcePersistentDisk:
    pdName: my-data-disk
    fsType: ext4
  accessModes:
    - ReadWriteOnce
